/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PBOP;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class FormTiket extends javax.swing.JFrame {

    /**
     * Creates new form FormTiket
     */
    public FormTiket() {
//        this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
//        this.setUndecorated(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Keluar = new javax.swing.JButton();
        JTiket = new javax.swing.JPanel();
        JadwalTiket = new javax.swing.JLabel();
        TableJadwal = new javax.swing.JTabbedPane();
        TabJadwal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        TabID = new javax.swing.JPanel();
        BTiket = new javax.swing.JPanel();
        BeliTiket = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 48)); // NOI18N
        jLabel1.setText("KAI ACCESS");
        jLabel1.setMaximumSize(new java.awt.Dimension(60, 120));
        jLabel1.setMinimumSize(new java.awt.Dimension(60, 120));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, -1));

        Keluar.setText("KELUAR");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        jPanel1.add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 110, -1));

        JTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JTiketMousePressed(evt);
            }
        });
        JTiket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JadwalTiket.setBackground(new java.awt.Color(51, 51, 255));
        JadwalTiket.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        JadwalTiket.setText(" JADWAL TIKET");
        JTiket.add(JadwalTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(JTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 100, 30));

        TabJadwal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(0, 51, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("KAI");
        TabJadwal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("KISARAN (KIS) > MEDAN (MDN)");
        TabJadwal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 230, -1));

        jLabel4.setText("Ekonomi (C)  :      13:15         >    17:21 WIB");
        TabJadwal.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 260, -1));

        jLabel5.setText("Bisnis (O)      :      10:08         >    13:27 WIB");
        TabJadwal.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 260, -1));

        jLabel6.setText("Eksekutif (A) :      09:00         >    12:00 WIB");
        TabJadwal.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("MEDAN (MDN) > KISARAN (KIS)");
        TabJadwal.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel8.setText("Ekonomi (C)  :      12:50         >    16:43 WIB");
        TabJadwal.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel9.setText("Bisnis (O)      :      15:00         >    18:33 WIB");
        TabJadwal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jLabel10.setText("Eksekutif (A) :      15:00         >    18:33 WIB");
        TabJadwal.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Kereta          Berangkat     :     Tiba");
        TabJadwal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Kereta          Berangkat     :     Tiba");
        TabJadwal.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 102, 255));
        TabJadwal.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 30));

        TableJadwal.addTab("TabJadwal", TabJadwal);

        TabID.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TableJadwal.addTab("TabID", TabID);

        jPanel1.add(TableJadwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 310, 380));

        BTiket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BTiketMousePressed(evt);
            }
        });
        BTiket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BeliTiket.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        BeliTiket.setText("    BELI TIKET");
        BTiket.add(BeliTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 30));

        jPanel1.add(BTiket, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 100, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        PKeluar();
    }//GEN-LAST:event_KeluarActionPerformed

    private void JTiketMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JTiketMousePressed
        // TODO add your handling code here:
        SetWarna(JTiket);
        ResetWarna(new JPanel []{BTiket});
        TableJadwal.setSelectedIndex(0);
    }//GEN-LAST:event_JTiketMousePressed

    private void BTiketMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTiketMousePressed
        // TODO add your handling code here:
         SetWarna(BTiket);
        ResetWarna(new JPanel []{JTiket});
        TableJadwal.setSelectedIndex(1);
    }//GEN-LAST:event_BTiketMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTiket.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTiket().setVisible(true);
            }
        });
        
    }
    private void SetWarna(JPanel pane){
        pane.setBackground(new Color(51,51,255));
        }
        private void ResetWarna(JPanel[] pane){
            for (int i = 0; i < pane.length; i++){
                pane[i].setBackground(new Color(255,255,255));
            }
        }
    
    public void PKeluar(){
        int dialogButton = JOptionPane.showConfirmDialog (null, "Apakah Anda Yakin Akan Keluar?","PERINGATAN",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);

        if(dialogButton == JOptionPane.YES_OPTION) {
        System.exit(0);}
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BTiket;
    private javax.swing.JLabel BeliTiket;
    private javax.swing.JPanel JTiket;
    private javax.swing.JLabel JadwalTiket;
    private javax.swing.JButton Keluar;
    private javax.swing.JPanel TabID;
    private javax.swing.JPanel TabJadwal;
    private javax.swing.JTabbedPane TableJadwal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
